name: Autocomplete Test Actions

on: [push]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node install
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Deploy vercel
        if: success()
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ secrets.ORG_ID }} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} #Required
